dofile, feature: more information

diff --git a/test/dofile b/test/dofile
--- a/test/dofile
+++ b/test/dofile
@@ -6,7 +6,13 @@ set -x
 
 echo "Testing: $1"
 "$CC" -std=gnu11 -Wall -Werror -Wno-unused -g -I.. "$1" -o $(basename "$1" .c)
+if [ $? -ne 0 ]; then
+  echo "Fail, nocompile: $1"
+fi
 ./$(basename "$1" .c)
-# If any of the above exits non-zero, we crash before here.
-echo "Pass: $1"
+if [ $? -ne 0 ]; then
+  echo "Fail: $1"
+else
+  echo "Pass: $1"
+fi
 rm $(basename "$1" .c)
